spring:
  application:
    name: ticket-assistant
  ai:
    dashscope:
      api-key: ${DASHSCOPE_ALI_API_KEY}
      chat:
        options:
          model: qwen-plus
    memory:
      redis:
        host: localhost
        port: 6379
        timeout: 5000
        password: 123456