spring:
  application:
    name: quick-start
  ai:
    deepseek:
      api-key: ${DEEP_SEEK_API_KEY}
      chat:
        options:
          model: deepseek-v4-flash
    dashscope:
      api-key: ${DASHSCOPE_ALI_API_KEY}
      chat:
        options:
          model: qwen-plus
