spring:
  application:
    name: chatclient
  ai:
    deepseek:
      api-key: ${DEEP_SEEK_API_KEY}
      chat:
        options:
          model: deepseek-v4-flash
    dashscope:
      api-key: ${DASHSCOPE_ALI_API_KEY}
      chat:
        options:
          model: qwen-plus

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug